language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpspec run -f pretty --no-interaction
  - vendor/bin/behat -fprogress --strict
